apiVersion: v2
name: microservices-app
description: Umbrella chart for the microservices application
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  # Microservices
  - name: microservice
    version: 0.1.0
    repository: file://charts/microservice
    alias: api-gateway
  - name: microservice
    version: 0.1.0
    repository: file://charts/microservice
    alias: user-service
  - name: microservice
    version: 0.1.0
    repository: file://charts/microservice
    alias: product-service
  - name: microservice
    version: 0.1.0
    repository: file://charts/microservice
    alias: order-service
  - name: microservice
    version: 0.1.0
    repository: file://charts/microservice
    alias: payment-service

  # Infrastructure (Local Charts)
  - name: mongodb
    version: 18.1.20
    repository: file://charts/mongodb
    alias: mongodb
  - name: kafka
    version: 32.4.3
    repository: file://charts/kafka
    alias: kafka
